### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by mkolopanis**
python-3-izes `hera_corr_cm`. Currently running on `qmaster` as a test after the conda environment was update to python-3.

Most additions on OCT 16 are formatting and one change of  `iteritems()` to `items()` when iterating over a dict.

### CODE REVIEW

**Comment by jack-h** [comment]
Is everything in here backwards compatible with python2?

**Comment by mkolopanis** [comment]
I think it'll actually need some `__future__` imports for that to get the absolute_imports and print functions to work properly. Looks like most of the heavy lifting was performed by `2to3` function.

**Comment by plaplant** [comment]
I think we might have to change some of the dictionary iteration to use `six.iteritems()` as well. Silly question, but does it have to be python2-compatible?

**Comment by mkolopanis** [comment]
`.items()` does _work_ on python2 it's just not very efficient

**Comment by mkolopanis** [comment]
I think the biggest thing about the different print syntax is just a little more readability. the only print syntax I know which would break things are f-strings and we don't have any of those. 

The first thing I can think that we might want to import from `__future__` is print_function. It behaves a little differently in python2 (see example below), but even then we don't print many things with comma separations I think, and all it really does is pretty up the stdout.  As for the absolute imports, I'm not sure if that is something we'll know without trying it (since there are no real tests we can execute for this code).

If we don't _need_ the imports then I'm fine not having them. I'm also in favor of helping things work in both for now. Not many changes in python 3 explicitly break python 2, but some string handling definitely does and It doesn't look like we use `basestring` in corr_cm anyway.


```
Python 2.7.16 |Anaconda, Inc.| (default, Sep 24 2019, 21:51:30) 
Type "copyright", "credits" or "license" for more information.

IPython 5.8.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: print("hello", "world")
('hello', 'world')

In [2]: from __future__ import print_function

In [3]: print("hello", "world")
hello world
```

**Comment by jack-h** [comment]
@mkolopanis That all sounds fine. If you want the future imports (sounds like you do) if you add them in to this PR I'll merge and try running on site and see what happens.
Thanks

**Comment by mkolopanis** [comment]
I seemed to have missed your last comment, I added the `from __future__ import print_function` call in the module files and the log_cm_bridge. I tested this branch on `hera-corr-cm` *without* these additions on [07 Nov during maintenance day](https://github.com/HERA-Team/HERA_Commissioning/issues/315). Things seemed to go well enough in the python 2 environment. Feel free to test again at your leisure.

**Pull request merged**
