### PR TITLE
changed ant status fields to new hera_corr_f

### PR DESCRIPTION
**Pull request by david-deboer**
Some slight changes to the redis keys for the ant status entries.  Adds three new fields:  clip_count, fem_pressure, fem_humidity.

These keys get inserted into redis on hera-snap-head by hera_snap_redis_monitor.py and read on qmaster by this repo.

### CODE REVIEW

**Review by bhazelton — COMMENTED** [review]
The added entries in the dict won’t break anything in hera_mc, but the removals will. I’d suggest not deleting those entries yet (but do add the new LNA power one). Then we can update hera_mc to use them and then come back and do the deletions. That way both repos don't have to change simultaneously.

**Comment by david-deboer** [comment]
The problem is that that call in hera_corr_cm doesn't know about polarization, so it can't ascertain if it is fem_e or fem_n.  Backward compatibility (ie to handle the hera_mc db key) should go into hera_mc.  We can "fake" it in hera_corr_cm for the time-being to keep hera_mc from breaking, but that will tie the two pols together in hera_corr_cm in the meantime (which actually shouldn't matter, but not something we want to keep.)

**Comment by david-deboer** [comment]
I've pushed one not very satisfactory way to fake it and will look to fix hera_mc (which can be fixed without need of an alembic change).  The other way, is to plumb a few things through in hera_corr_cm in the interim but it would be clunky.  I'd prefer to fake it and fix it the first way since it is easier to fix it in hera_mc than to accurately fake it in hera_corr_cm

**Review by bhazelton — APPROVED** [review]
This seems reasonable. I sure wish there was a way to test things on this repo!

**Pull request merged**
